### ISSUE TITLE
Please Add Tags

### ISSUE THREAD

**Issue by usert5432** [LS4GAN/toyzero#9] opened 2021-07-15 18:53 UTC
Hi @brettviren,

I am trying to use toyzero to generate a dataset, but the code is constantly changing, and I am failing to keep up with the changes (e.g. what does `mv -> cp` change do)? I was wondering if it would be possible to add tags with a small changelog annotations to the toyzero repo? They will help to navigate the changes and ensure that we all rely on the same code for the data generation.

For example, the commit 3b0d0839c1d7ba67426809d362b66b7094cf7731 was the first version that we tried to run to generate the dataset. It could be the tag v0.0.1. Now, as the the 5k bug was fixed and a config introduced, we can create a tag v0.1.0 (based on 53dc8088510f303f62bfee0f37317878d73eea5f) and use it for future data generation?

**Comment by brettviren** [comment] 2021-07-15 19:57
> what does mv -> cp change

This was a technical thing to fix an interment failure.  I think the problem is the `mv` broke snakemake's dependency chain.  I could only trigger it on a fresh build and sometimes it worked so hadn't noticed a problem until now.

I'd prefer to try to make more verbose commit messages than to maintain an explicit changelog.  I will also stop pushing directly and instead switch to making PRs.  These will give a "place" were we can pause, read, make comments, etc, before merging.

I'll make the tags as you suggest.  This is a very good idea.


BTW, I next want to extend the Snakefile with optional rules that will allow running with noise simulation, then follow with noise filter + signal processing and then 3D imaging.  These will not be run via the `all` or `just_images` and those rules should continue to produce the same results.

**Comment by brettviren** [comment] 2021-07-16 14:41
I pushed the tags which I'll count as enough to close this issue.  Of course reopen if needed.

**Closed by brettviren** 2021-07-16 14:41 UTC

**Comment by usert5432** [comment] 2021-07-16 15:10
Thanks!
